oneblink/apps-react

CHANGELOG.md
package-lock.json
package.json
src/services/sanitize-html.ts

- fixed img elements being filtered out
- also made build script cross platform

ON-9476 # Allow Images in HTML sanitisation

---

CHANGELOG.md
src/OneBlinkFormBase.tsx
src/components/renderer/PageFormElements.tsx
src/form-elements/FormElementForm.tsx
src/form-elements/FormElementSection.tsx
src/hooks/useFormSubmissionAutoSaveState.ts
src/hooks/useFormSubmissionState.tsx
src/hooks/useLookups.ts
src/types/form.ts

Reverts oneblink/apps-react#367

Revert "ON-29891 # Add lastElementUpdated and store in autoSave data"

---

CHANGELOG.md
src/OneBlinkFormBase.tsx
src/hooks/usePages.ts

Reverts oneblink/apps-react#393

Revert "ON-30538 # Fixed validation not displaying on unvisited pages when su…"

---

CHANGELOG.md
src/hooks/useInfiniteScrollDataLoad.tsx

Reverts oneblink/apps-react#430

Revert "ON-31465 # `useInfiniteScrollDataLoad` optionally return `total` if p…"

---

CHANGELOG.md
src/hooks/attachments/useAttachment.ts

Reverts oneblink/apps-react#623

Revert "ON-38765 # default content type to `application/octet-stream` when up…"

---

package-lock.json
package.json
src/components/renderer/ReverseGeocode.tsx

ON-39872 # remove google maps reverse geocoding

---

CHANGELOG.md
src/OneBlinkFormBase.tsx
src/components/MaterialIcon.tsx
src/components/renderer/FormElementLabelContainer.tsx
src/components/renderer/PageFormElements.tsx
src/form-elements/FormElementCompliance.tsx
src/form-elements/FormElementRepeatableSet.tsx
src/form-elements/FormElementSection.tsx

ON-43426 # added support for WCAG 1.3.1 - Info and Relationships

---

src/components/renderer/PageFormElements.tsx
src/form-elements/FormElementCompliance.tsx
src/form-elements/FormElementRepeatableSet.tsx
src/form-elements/FormElementSection.tsx

ON-43566 # add region role to elements

---

src/components/renderer/OneBlinkFormElements.tsx
src/form-elements/FormElementSection.tsx

ON-43579 # move aria region for FormElementSections

---

src/components/renderer/FormElementLabelContainer.tsx

ON-43581 # revert tooltip to using i tag

---

CHANGELOG.md
package-lock.json
src/components/renderer/AutocompleteDropdown.tsx
src/components/renderer/OneBlinkFormElements.tsx
src/form-elements/FormElementABN.tsx
src/form-elements/FormElementAPINSWLiquorLicence.tsx
src/form-elements/FormElementAutocomplete.tsx
src/form-elements/FormElementBSB.tsx
src/form-elements/FormElementBarcodeScanner.tsx
src/form-elements/FormElementCivicaStreetName.tsx
src/form-elements/FormElementCompliance.tsx
src/form-elements/FormElementDate.tsx
src/form-elements/FormElementDateTime.tsx
src/form-elements/FormElementEmail.tsx
src/form-elements/FormElementGeoscapeAddress.tsx
src/form-elements/FormElementGoogleAddress.tsx
src/form-elements/FormElementNumber.tsx
src/form-elements/FormElementPointAddress.tsx
src/form-elements/FormElementSelect.tsx
src/form-elements/FormElementTelephone.tsx
src/form-elements/FormElementText.tsx
src/form-elements/FormElementTextarea.tsx
src/form-elements/FormElementTime.tsx

ON-43438 # Added `autocompleteAttributes` to elements

---

CHANGELOG.md
src/components/payments/PaymentForm.tsx
src/components/renderer/LookupNotification.tsx
src/components/renderer/OnLoading.tsx
src/components/renderer/attachments/AttachmentStatus.tsx
src/form-elements/FormElementArcGISWebMap.tsx
src/form-elements/FormElementBarcodeScanner.tsx
src/form-elements/FormElementCamera.tsx
src/form-elements/FormElementLocation.tsx
src/form-elements/FormElementSignature.tsx

ON-43481 # added support for WCAG 4.1.3 - Status Messages

---

src/hooks/usePages.ts

ON-43653 # Remove WIP after using release cli

---

src/components/messages/ErrorMessage.tsx
src/components/messages/LargeIconMessage.tsx
src/components/renderer/LookupNotification.tsx

ON-43692 # added alert role to ErrorMessage component

---

CHANGELOG.md
package-lock.json
src/OneBlinkFormBase.tsx
src/components/payments/WestpacQuickStreamPaymentForm.tsx
src/form-elements/FormElementCaptcha.tsx
src/hooks/useCaptcha.ts
src/hooks/useCaptchaSiteKey.ts
src/hooks/useFormValidation.ts
src/hooks/useReCAPTCHAProps.ts
src/services/form-validation.ts
src/types/form.ts
src/types/validate.js.d.ts

ON-43678 # added support for invisible recaptcha

---

src/OneBlinkFormBase.tsx

ON-43802 # don't reset invisible recaptchas

---

src/components/payments/PaymentForm.tsx

ON-43805 # add captchaType prop to PaymentForm

---

src/styles/renderer.scss

ON-43977 # Altered tooltip background, link and visited link colors

---

src/OneBlinkFormBase.tsx

ON-44002 # Submission disabled tooltip and class

---

src/OneBlinkFormBase.tsx

ON-44015 # Fix when `ob-button-submit-is-disabled` is added

---

src/OneBlinkFormBase.tsx
src/components/renderer/CopyToClipboardButton.tsx
src/components/renderer/FormElementLabelContainer.tsx
src/components/renderer/Tooltip.tsx
src/components/renderer/attachments/AttachmentStatus.tsx
src/form-elements/FormElementSection.tsx
src/hooks/useOneBlinkFormContainer.ts

ON-44005 # move Tooltip container to the OneBlinkForm container

---

src/components/renderer/attachments/DropdownMenu.tsx
src/components/renderer/attachments/FileCard.tsx

ON-44115 # Conditionally open in new tab option

---

src/components/renderer/attachments/DropdownMenu.tsx

ON-44139 # changed open file icon styling

---

src/components/renderer/attachments/DropdownMenu.tsx

ON-44156 # fixed files dropdown not closing when selecting "open"

---

CHANGELOG.md
src/styles/ob-html.scss

ON-44175 # override ql-editor strong styles

---

src/components/ValidationErrorsCard.tsx

ON-44183 # Made offset a negative

---

src/styles/validation-errors-card.scss

ON-44212 # Fixed error message string truncation

---

src/OneBlinkFormBase.tsx
src/components/renderer/OneBlinkFormElements.tsx

ON-44219 # Fixed last element edited regression

---

src/OneBlinkFormBase.tsx

ON-44281 # Support not using the new validation errors toast

---

src/OneBlinkFormBase.tsx
src/components/ValidationErrorsCard.tsx
src/utils/scrollToElement.ts

ON-44322 # Added a prop to pass in a scrollable container id

---

CHANGELOG.md
package-lock.json
src/OneBlinkFormBase.tsx

ON-44553 # Fixed autosave data to be saved again after successful form submission

---

package-lock.json
package.json

ON-44866 # Bumped @oneblink/sdk-core

---

src/form-elements/FormElementTextarea.tsx

ON-44941 # set a min and max rows in the textarea

---

CHANGELOG.md
src/hooks/useConditionalLogic.ts

ON-45067 # Fixed submit button conditional logic not taking into account conditional elements

---

src/index.ts

ON-45118 # Add default `useAppUserMfa` export

---

CHANGELOG.md
package-lock.json
package.json
src/components/calendar-bookings/CalendarBookingsCancelForm.tsx
src/components/calendar-bookings/CalendarBookingsContainer.tsx
src/components/calendar-bookings/CalendarBookingsForm.tsx
src/components/calendar-bookings/CalendarBookingsProvider.tsx
src/components/calendar-bookings/CalendarBookingsReschedulingForm.tsx
src/components/calendar-bookings/ErrorModal.tsx
src/components/calendar-bookings/calendar-booking-form.scss
src/index.ts

ON-45150 # add CalendarBookingsForm and related components

---

src/hooks/useMfa.tsx

ON-45197 # added isExternalIdentityProviderUser to useMfa context

---

src/services/form-validation/validate-dot-js.ts
src/services/form-validation/validateSubmission.ts

ON-45348 # Fixed boolean required validation

---

src/services/form-validation/validateSubmission.ts

ON-45389 # Fixed repeatable set and invalid file names validation

---

CHANGELOG.md
src/form-elements/OptionButton.tsx

ON-45212 # Add display of images for Checkboxes and Radio button options

---

CHANGELOG.md
src/OneBlinkFormBase.tsx
src/form-elements/FormElementCaptcha.tsx
src/hooks/useFormValidation.ts
src/services/form-validation/extensions.ts
src/services/form-validation/validateSubmission.ts

ON-45360 # Added offline validation message for recaptcha

---

src/services/form-validation/validateSubmission.ts

ON-45398 # Fixed repeatable set lookup validation

---

package-lock.json
package.json
src/services/form-validation/validate-dot-js.ts

ON-45381 # use email-validator in place of validate.js email regex

---

src/form-elements/FormElementCaptcha.tsx
src/services/form-validation/validateSubmission.ts

ON-45412 # do not display captcha element if user is offline

---

src/services/form-validation/validate-dot-js.ts
tests/services/form-validation/validate-dot-js.test.ts

ON-45413 # Added unit tests for validators

---

src/styles.scss
src/styles/option-buttons.scss

ON-45494 # added default styles for option images

---

package-lock.json
package.json
src/PaymentReceipt.tsx

ON-45596 # fix executePostSubmissionAction

---

CHANGELOG.md
package-lock.json
package.json
src/OneBlinkFormBase.tsx
src/components/renderer/LookupButton.tsx
src/services/form-validation/validators.ts

ON-45820 # Changed captchaTokens to recaptchas

---

CHANGELOG.md
package-lock.json
package.json
src/components/formStore/table/useFormStoreTable.tsx

ON-45901 # Added task columns to data manager

---

CHANGELOG.md
src/styles/buttons.scss

ON-46016 # set .ob-button min-width to 140px

---

CHANGELOG.md
package-lock.json
package.json
src/components/payments/WestpacQuickStreamPaymentForm.tsx

ON-46260 # Updated apps; passing `captchaSiteKey` alongside token

---

CHANGELOG.md
package-lock.json
src/form-elements/FormElementRepeatableSet.tsx
src/styles/repeatable-set.scss

ON-46230 # handle SINGLE_ADD_BUTTON and MULTIPLE_ADD_BUTTONS

---

src/form-elements/FormElementRepeatableSet.tsx

ON-46424 # Fixed repeatable set entries being inserted at incorrect index

---

src/form-elements/FormElementRepeatableSet.tsx

ON-46440 # Added primary colour to multiple add buttons repeatable set

---

src/form-elements/FormElementRepeatableSet.tsx
src/services/generate-default-data.ts
src/styles/repeatable-set.scss
tests/services/generate-default-data.test.ts

ON-46457 # Added collapse animation for repeatable set entries

---

src/form-elements/FormElementRepeatableSet.tsx
src/services/cleanFormSubmissionModel.ts
src/services/generate-default-data.ts
tests/services/generate-default-data.test.ts

ON-46526 # Fixed prefill data for repeatable sets and submission data for civica name element

---

CHANGELOG.md
src/form-elements/OptionButton.tsx

ON-46790  # allow screen readers to ignore optionSet images

---

CHANGELOG.md
src/services/sanitize-html.ts

ON-47071 # Remove `sanitizeCustomCSS()`

---

src/components/formStore/table/Pickers.tsx
src/form-elements/FormElementDate.tsx
src/form-elements/FormElementDateTime.tsx
src/form-elements/FormElementTime.tsx
src/hooks/form-date-picker/useFormDatePickerProps.tsx

ON-47169 # add cypress classes to date picker elements

---

CHANGELOG.md
jest.config.json
package-lock.json
package.json
src/components/formStore/table/FormElementTableCell.tsx
src/form-elements/FormElementCalculation.tsx
src/form-elements/FormElementDate.tsx
src/form-elements/FormElementDateTime.tsx
src/form-elements/FormElementSummary.tsx
src/form-elements/FormElementTime.tsx
src/hooks/form-date-picker/useFormDatePickerProps.tsx
src/services/form-validation/validateSubmission.ts
src/services/generate-default-data.ts
src/styles.scss
src/styles/date.scss

Reverts oneblink/apps-react#795

Revert "ON-47182 # switch to native date, datetime-local and time inputs"

---

CHANGELOG.md
src/PaymentReceipt.tsx

ON-47209 # Add download PDF button to payment receipt

---

src/PaymentReceipt.tsx

ON-47302 # changed payment receipt download PDF button styling

---

src/hooks/form-date-picker/useFormDatePickerProps.tsx

ON-47303 # Fixed picker going to top left of page on close

---

src/form-elements/FormElementDate.tsx
src/form-elements/FormElementDateTime.tsx
src/form-elements/FormElementTime.tsx
src/hooks/form-date-picker/useFormDatePickerProps.tsx

ON-47386 # Allow text input for date/datetime/time elements

---

package-lock.json
package.json
src/hooks/form-date-picker/useFormDatePickerProps.tsx

ON-47396 # run blur function from the picker first then set field dirty

---

src/components/renderer/OneBlinkFormElements.tsx
src/form-elements/FormElementDate.tsx
src/form-elements/FormElementDateTime.tsx
src/form-elements/FormElementTime.tsx
src/hooks/form-date-picker/useFormDatePickerProps.tsx
src/styles.scss
src/styles/date.scss

ON-47414 # stop supporting autocomplete for date, datetime and time elements

---

src/hooks/form-date-picker/useFormDatePickerProps.tsx

ON-47485 # Added testing class to date/time picker button

---

src/hooks/form-date-picker/useFormDatePickerProps.tsx

ON-47484 # add preventOverflow modifiers to popper

---

src/hooks/form-date-picker/useFormDatePickerProps.tsx

ON-47490 # open mobile clicker when clicking input on mobile

---

src/form-elements/FormElementDate.tsx
src/form-elements/FormElementDateTime.tsx

ON-47494 # fix tenant race condition and date value parsing

---

CHANGELOG.md
package-lock.json
src/form-elements/FormElementPointAddress.tsx

OB-2365 # Added address information display to point address form element

---

package-lock.json
package.json
src/hooks/useDynamicOptionsLoaderState.tsx

OB-2383 # Bumped @oneblink/apps

---

package-lock.json
src/components/NotificationGrid.tsx
src/form-elements/FormElementAPINSWLiquorLicence.tsx
src/form-elements/FormElementPointAddress.tsx
src/styles.scss
src/styles/nsw-point-address.scss

OB-2430 # Fixed media query not catering for embedded forms

---

CHANGELOG.md
package-lock.json
src/components/ArcGISWebMap.tsx
src/components/renderer/OneBlinkFormElements.tsx
src/form-elements/FormElementArcGISWebMap.tsx
src/services/generate-default-data.ts

ON-47881 # added sketch widget to ArcGIS Web Map element

---

src/components/ArcGISWebMap.tsx

ON-48018 # ArcGIS map ui tweaks

---

src/components/ArcGISWebMap.tsx
src/components/renderer/OneBlinkFormElements.tsx
src/form-elements/FormElementArcGISWebMap.tsx
src/services/form-validation/validateSubmission.ts

ON-48019 # ArcGIS element validation

---

src/services/generate-default-data.ts

ON-48022 # fixed pre-fill validation for ArcGISWebMap element

---

tests/services/generate-default-data.test.ts

ON-48034 # added tests to generate-default-data for arcGISWebMap element

---

src/components/ArcGISWebMap.tsx
src/form-elements/FormElementArcGISWebMap.tsx

ON-48050 # Arcgis map read only drawing layer

---

src/form-elements/FormElementPointCadastralParcel.tsx

AP-2691 # Changed cadastral parcel input to debounce search

---

src/components/ArcGISWebMap.tsx

ON-48057 # ArcGIS sketch tool requiring allowed draw tools

---

src/components/ArcGISWebMap.tsx

ON-48063 # Allow arcgis drawing on lookup failure

---

package-lock.json
src/components/ArcGISWebMap.tsx
src/form-elements/FormElementArcGISWebMap.tsx

Reverts oneblink/apps-react#830

Revert "AP-2692 # Changed props for esri map component to prevent recursive i…"

---

src/components/ArcGISWebMap.tsx

MS-76 # fixed drawing tools not displaying in consistent order

---

src/components/ArcGISWebMap.tsx

MS-81 # Unique dom ID for drawing options container

---

CHANGELOG.md
package-lock.json
src/components/Clickable.tsx
src/components/ValidationErrorsCard.tsx
src/form-elements/FormElementLocation.tsx
src/form-elements/FormElementRepeatableSet.tsx
src/styles/validation-errors-card.scss
src/utils/scrollToElement.ts

AP-2993 # Fixed accessibility on validation toast

---

src/OneBlinkFormBase.tsx
src/components/ValidationErrorsCard.tsx

Closes AP-3027
- When reviewing tests, attempt to identify missing edge cases that may be relevant to the …

AP-3028 # Fixed validation toast not being focused when clicking submit

---

src/OneBlinkFormBase.tsx

AP-3034 # Fixed validation toast showing without clicking submit

---

CHANGELOG.md
src/OneBlinkAutoSaveForm.tsx
src/OneBlinkFormBase.tsx
src/types/global.d.ts
src/utils/sendGAEvents.ts

MS-177 # push submit and abandon events to google analytics

---

src/OneBlinkFormBase.tsx

MS-213 # Send event when form is cancelled without any modifications

---

CHANGELOG.md
src/form-elements/FormElementCamera.tsx
src/hooks/attachments/useAttachments.ts
src/services/attachments.ts

AP-3150 # Added validation to prevent uploading empty files

---

CHANGELOG.md
package-lock.json
src/OneBlinkFormBase.tsx
src/components/ValidationErrorsCard.tsx
src/hooks/usePages.ts
src/services/form-validation/validateSubmission.ts
src/services/generateConfirmationFormElement.ts

AP-3217 # Added requiresConfirmation support for email form elements

---

CHANGELOG.md
src/utils/scrollToElement.ts

ap-3256 # Fixed error validation toast scrolling animations

---

CHANGELOG.md
package-lock.json
src/form-elements/FormElementBoolean.tsx

MS-248 # Add `displayAsCheckbox` support for Switch element

---

src/components/renderer/PageFormElements.tsx

AP-3270 # Fixed page lookup handler using page elements as a dependency

---

src/hooks/usePages.ts
src/services/dynamic-elements.ts
src/services/form-validation/validateSubmission.ts
src/services/generateConfirmationFormElement.ts

ap-3275 # Removed some logic not needed. Moved dynamic elements logic

---

CHANGELOG.md
src/hooks/attachments/useAttachment.ts

AP-3284 # Fixed attachment not uploaded if file is not stored locally successfully

---

CHANGELOG.md
src/components/ArcGISWebMap.tsx

MS-332 # Change location of controls on ArcGIS Web Map element

---

CHANGELOG.md
package-lock.json
src/components/ArcGISWebMap.tsx

MS-361 # changed ArcGIS Web Map element layer update handling

---

package-lock.json
package.json

MS-393 # Bumped @oneblink/sdk-core

---

src/OneBlinkFormBase.tsx
src/components/renderer/PageFormElements.tsx
src/hooks/useFormSubmissionState.tsx
src/types/form.ts

MS-417 # optional collapsedSectionIds

---

package-lock.json
package.json
src/OneBlinkFormBase.tsx

MS-443 # Include `sectionState` in `onSaveDraft()`

---

CHANGELOG.md
src/services/form-validation/extensions.ts

AP-3827 # fix nested lookup validation

---

package-lock.json
package.json
src/OneBlinkAutoSaveForm.tsx
src/OneBlinkForm.tsx
src/OneBlinkFormBase.tsx
src/hooks/useFormSubmissionAutoSaveState.ts
src/hooks/useFormSubmissionState.tsx

MS-451 # Restore section state when resuming draft

---

src/components/renderer/OneBlinkFormElements.tsx
src/form-elements/FormElementForm.tsx
src/form-elements/FormElementRepeatableSet.tsx
src/form-elements/FormElementSection.tsx
src/types/form.ts

MS-466 # Fix saving/loading nested section elements state

---

package-lock.json
package.json
src/OneBlinkFormBase.tsx
src/form-elements/FormElementRepeatableSet.tsx
src/types/form.ts

MS-496 # Update section state on repeatable set entry delete

---

src/OneBlinkFormBase.tsx
src/form-elements/FormElementForm.tsx
src/form-elements/FormElementRepeatableSet.tsx
src/form-elements/FormElementSection.tsx
src/types/form.ts

MS-516 # fixed section state not tracking nested sections correctly

---

src/components/ArcGISWebMap.tsx
src/components/renderer/AutocompleteDropdown.tsx
src/form-elements/FormElementAPINSWLiquorLicence.tsx
src/form-elements/FormElementArcGISWebMap.tsx
src/form-elements/FormElementAutocomplete.tsx
src/form-elements/FormElementCivicaStreetName.tsx
src/form-elements/FormElementGeoscapeAddress.tsx
src/form-elements/FormElementGoogleAddress.tsx
src/form-elements/FormElementPointAddress.tsx

AP-3916 # Fixed missing aria-required prop on autocomplete inputs

---

src/OneBlinkFormBase.tsx
src/form-elements/FormElementRepeatableSet.tsx

MS-519 # further fixes to section state updates within repeatable sets

---

CHANGELOG.md
package-lock.json
package.json
src/components/formStore/table/FormElementTableCell.tsx
src/components/renderer/LookupNotification.tsx
src/components/renderer/OneBlinkFormElements.tsx
src/form-elements/FormElementLookupButton.tsx
src/services/cleanFormSubmissionModel.ts
src/services/form-validation/determineLookupButtonIsRequired.ts
src/services/form-validation/validateSubmission.ts
src/services/generate-default-data.ts

AP-3855 # Added lookup button form element

---

CHANGELOG.md
package-lock.json
src/OneBlinkFormBase.tsx
src/components/OneBlinkFormFooter.tsx
src/styles/renderer.scss

ap-3895 # Added footer rendering

---

src/form-elements/FormElementLookupButton.tsx
src/form-elements/FormElementText.tsx
src/form-elements/FormElementTextarea.tsx

AP-3983 # Fixed lookup button being disabled if there are no dependent elements

---

src/OneBlinkFormBase.tsx

AP-3995 # wrap context around footer only

---

CHANGELOG.md
package-lock.json
package.json
src/form-elements/FormElementFiles.tsx
src/hooks/attachments/useAttachments.ts

MS-526 # `maxFileSize` validation for `files` element

---

src/form-elements/FormElementFiles.tsx
src/hooks/attachments/useAttachments.ts

MS-533 # fix params passed to useAttachments()

---

CHANGELOG.md
package-lock.json
package.json
src/components/formStore/table/getVersionedState.ts
src/components/formStore/table/useFormStoreTable.tsx
tests/components/form-store/table.test.ts

AP-3934 # Added dateTimeCompleted to form store table

---

CHANGELOG.md
src/components/ArcGISWebMap.tsx

MS-457 # added handling for ArcGIS web map layer visibility

---

CHANGELOG.md
src/OneBlinkReadOnlyForm.tsx
src/form-elements/FormElementForm.tsx

 MS-480 # added read-only functionality to "Form" form elements

---

package-lock.json
package.json

MS-567 # bumped @oneblink/apps

---

package-lock.json
package.json
src/hooks/attachments/useAttachments.ts
src/services/attachments.ts
src/services/form-validation/validators.ts

MS-605 # Display different validation message for maxFileSize

---

CHANGELOG.md
src/components/ArcGISWebMap.tsx

AP-4245 # respect submission layers and keep drawing layer on the top

---

package-lock.json
package.json

AP-4322 # Bumped @oneblink/sdk-core

---

src/components/ArcGISWebMap.tsx

AP-4416 # initialise stringifedLayersRef to an empty string

---

src/components/ArcGISWebMap.tsx

AP-4453 # measurement layer back to map on repaint

---

src/components/ArcGISWebMap.tsx
src/form-elements/FormElementArcGISWebMap.tsx
src/services/form-validation/validateSubmission.ts

AP-4475 # Removed imports of lazy load arc gis files

---

src/styles/arcgis-web-map.scss

ap-4441 # Added border-radius to esri-view-surface

---

package-lock.json
package.json

AP-4474 # Bumped @oneblink/sdk-core

---

CHANGELOG.md
src/styles/arcgis-web-map.scss

AP-4351 # fixed unintended center alignment of ESRI map text

---

src/components/downloadable-files/resource-components.tsx

ap-4593 # Added `unmountOnExit` to collapses

---

src/PaymentReceipt.tsx

AP-4605 # Fixed attachments loading when payments fail

---

src/components/downloadable-files/resource-components.tsx

ap-4628 # Downloadable files are now maximum 2 per line

---

CHANGELOG.md
package-lock.json
src/hooks/attachments/useAttachment.ts
src/services/download-file.ts

AP-4857 # Removed path from form submission attachments

---

src/hooks/attachments/useAttachment.ts
src/services/generate-default-data.ts

AP-4873 # Fixed URL origin not changing before downloading

---

CHANGELOG.md
src/OneBlinkFormBase.tsx
src/hooks/useDynamicOptionsLoaderState.tsx

AP-4833 # don't fetch dynamic options on read only forms

---

CHANGELOG.md
src/services/generate-default-data.ts

AP-5212 # allow prefilling snapshotImages in arcGISWebMap element

---

CHANGELOG.md
src/components/payments/WestpacQuickStreamPaymentForm.tsx

AP-5217 # fix reCAPTCHA component in WestpacQuickStreamPaymentForm

---

src/OneBlinkFormBase.tsx
src/components/payments/WestpacQuickStreamPaymentForm.tsx

AP-5224 # reset recaptchas before repayment
